In [5]:
from sklearn import datasets
iris = datasets.load_iris()

#forecasters attributes
x = iris.data
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
#awnswers
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x = scaler_x.fit_transform(x)
x

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [8]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categorical_features = [0])
y = y.reshape(-1, 1)

In [9]:
y.shape

(150, 1)

In [10]:
y = onehot.fit_transform(y).toarray()
y

C:\Users\fabio\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\fabio\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size = 0.3)

In [12]:
x_treinamento.shape

(105, 4)

In [13]:
x_teste.shape

(45, 4)

In [14]:
import tensorflow as tf
import numpy as np

In [15]:
neuronios_entrada = x.shape[1]
neuronios_entrada

4

In [18]:
neuronios_oculta = int(np.ceil((x.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [19]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [ ]:
#Weights
w = {'oculta': tf.Variable(tf.random_normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_oculta, neuronios_saida]))}

In [21]:
#Bias Weights
b = {'oculta': tf.Variable(tf.random_normal([neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_saida]))}

In [22]:
xph = tf.placeholder('float', [None, neuronios_entrada])
yph = tf.placeholder('float', [None, neuronios_saida])

In [23]:
def mlp(x, w, bias):
    camada_oculta = tf.add(tf.matmul(x, w['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, w['saida']), b['saida'])
    return camada_saida

In [24]:
modelo = mlp(xph, w, b)

In [31]:
erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = modelo, labels = yph))
otimizador = tf.train.AdamOptimizer(learning_rate = 0.0001).minimize(erro)

In [27]:
batch_size = 8
batch_total = int(len(x_treinamento) / batch_size)
batch_total

13

In [28]:
x_batches = np.array_split(x_treinamento, batch_total)
x_batches

[array([[ 1.28034050e+00,  9.82172869e-02,  6.49083415e-01,
          3.95774101e-01],
        [-1.02184904e+00, -1.74335684e+00, -2.60315415e-01,
         -2.62386821e-01],
        [-1.26418478e+00,  9.82172869e-02, -1.22655167e+00,
         -1.31544430e+00],
        [-9.00681170e-01,  1.47939788e+00, -1.28338910e+00,
         -1.05217993e+00],
        [ 5.53333275e-01, -8.22569778e-01,  6.49083415e-01,
          7.90670654e-01],
        [-4.16009689e-01, -1.05276654e+00,  3.64896281e-01,
          8.77547895e-04],
        [-5.37177559e-01,  7.88807586e-01, -1.16971425e+00,
         -1.31544430e+00],
        [-1.73673948e-01, -3.62176246e-01,  2.51221427e-01,
          1.32509732e-01],
        [-1.26418478e+00,  7.88807586e-01, -1.05603939e+00,
         -1.31544430e+00]]),
 array([[-1.14301691,  0.09821729, -1.2833891 , -1.44707648],
        [-0.41600969, -1.28296331,  0.13754657,  0.13250973],
        [-0.17367395,  1.70959465, -1.16971425, -1.18381211],
        [-1.14301691, -0.1319

In [30]:
x_batches[1]

array([[-1.14301691,  0.09821729, -1.2833891 , -1.44707648],
       [-0.41600969, -1.28296331,  0.13754657,  0.13250973],
       [-0.17367395,  1.70959465, -1.16971425, -1.18381211],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-0.65834543,  1.47939788, -1.2833891 , -1.3154443 ],
       [-1.50652052,  0.78880759, -1.34022653, -1.18381211],
       [ 1.15917263, -0.13197948,  0.99010798,  1.18556721],
       [-1.62768839, -1.74335684, -1.39706395, -1.18381211]])

In [36]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoca in range(3000):
        erro_medio = 0.0
        batch_total = int(len(x_treinamento) / batch_size)
        x_batches = np.array_split(x_treinamento, batch_total)
        y_batches = np.array_split(y_treinamento, batch_total)
        for i in range(batch_total):
            x_batch, y_batch = x_batches[i], y_batches[i]
            _, custo = sess.run([otimizador, erro], feed_dict = {xph: x_batch, yph: y_batch})
            erro_medio += custo / batch_total
        if epoca % 500 == 0:
                print('Época: ' + str((epoca + 1)) + ' Erro: ' + str(erro_medio))
    w_final, b_final = sess.run([w, b])

Época: 1 Erro: 1.5277584928732653
Época: 501 Erro: 0.3621397981276879
Época: 1001 Erro: 0.15599302417383745
Época: 1501 Erro: 0.06701856221144017
Época: 2001 Erro: 0.03546316070983617
Época: 2501 Erro: 0.02280236489605159


In [37]:
w_final

{'oculta': array([[ 0.9680483 , -1.0812945 , -0.1388013 ,  0.41468498],
        [-1.1193552 ,  0.57524514, -0.31801933, -0.5355411 ],
        [ 0.8064455 , -2.3075414 , -0.42303744,  0.24451418],
        [ 1.6334333 , -1.3405715 , -1.270984  , -1.7891957 ]],
       dtype=float32), 'saida': array([[-1.960378  , -0.82219404,  1.744758  ],
        [ 2.8003242 , -1.854555  , -2.6691856 ],
        [-1.5506474 ,  0.8344516 , -1.1138763 ],
        [ 0.436841  ,  1.4784642 , -2.2492697 ]], dtype=float32)}

In [38]:
b_final

{'oculta': array([-0.46781817, -0.17627892,  2.1657221 ,  1.120517  ], dtype=float32),
 'saida': array([-1.8246458,  1.3160594,  1.0148803], dtype=float32)}

In [44]:
#Previsions
previsoes_teste = mlp(xph, w_final, b_final)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    r1 = sess.run(previsoes_teste, feed_dict = {xph: x_teste})
    r2 = sess.run(tf.nn.softmax(r1))
    r3 = sess.run(tf.argmax(r2, 1))

In [41]:
r1

array([[ 12.26402   ,  -4.7822986 , -27.095339  ],
       [ -6.128094  ,   2.5573266 ,  -2.8151581 ],
       [ -4.253356  ,  -1.1027048 ,   2.4833765 ],
       [ -3.1618683 ,   0.5373864 ,  -0.47395188],
       [ 11.507315  ,  -3.391525  , -28.634474  ],
       [ -4.0657763 ,   2.6478372 ,  -3.4997387 ],
       [-10.352066  ,  -3.6605399 ,   7.911296  ],
       [ -8.419521  ,   2.2968018 ,  -1.9114299 ],
       [ -4.8414984 ,   3.3371994 ,  -4.368868  ],
       [ -4.866938  ,  -0.93148595,   2.3096364 ],
       [ -7.9496717 ,  -2.6529613 ,   5.773138  ],
       [ 13.696761  ,  -6.2843857 , -26.62204   ],
       [ -6.6297035 ,   5.9917793 ,  -8.122579  ],
       [ -5.704466  ,   0.46234655,   0.31769335],
       [ -7.7247005 ,  -2.345612  ,   5.215151  ],
       [ -3.9252975 ,   4.6146965 ,  -6.69005   ],
       [ -2.8779395 ,   1.2888036 ,  -1.7137363 ],
       [ -5.6336584 ,  -1.6816115 ,   3.711861  ],
       [ -5.838101  ,  -0.31588465,   1.5656729 ],
       [ -8.550849  ,   2.41044

In [43]:
r2

array([[1.00000000e+00, 7.74482523e-09, 2.07347233e-16],
       [5.35733474e-04, 6.21030748e-01, 3.78433555e-01],
       [4.61223608e-05, 2.11035629e-04, 9.99742806e-01],
       [2.58389674e-03, 2.04632785e-02, 9.76952791e-01],
       [9.99999881e-01, 6.63207587e-08, 9.48186350e-17],
       [4.81541222e-03, 7.77056694e-01, 2.18127981e-01],
       [4.55062710e-10, 7.18287936e-08, 9.99999881e-01],
       [3.83421466e-05, 3.38727295e-01, 6.61234319e-01],
       [1.35016977e-03, 9.42944109e-01, 5.57057895e-02],
       [2.97070765e-05, 2.97947059e-04, 9.99672413e-01],
       [4.26587512e-08, 1.66906773e-06, 9.99998331e-01],
       [1.00000000e+00, 4.11559009e-10, 7.94360865e-17],
       [1.68413044e-05, 9.99885798e-01, 9.73373899e-05],
       [9.34352574e-05, 8.72685015e-03, 9.91179764e-01],
       [9.33342506e-08, 3.96536689e-06, 9.99995947e-01],
       [9.95083945e-04, 9.97392774e-01, 1.61210680e-03],
       [1.04138087e-02, 1.31624684e-01, 8.57961535e-01],
       [3.39644612e-06, 3.46346

In [45]:
r3

array([0, 1, 2, 2, 0, 1, 2, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1, 2, 2, 1, 0, 1,
       2, 1, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2,
       0], dtype=int64)

In [47]:
y_teste2 = np.argmax(y_teste, 1)
y_teste2

array([0, 1, 2, 1, 0, 1, 2, 2, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2, 2, 1, 0, 1,
       2, 2, 1, 0, 2, 2, 2, 0, 2, 1, 1, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2,
       0], dtype=int64)

In [51]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, r3)
print(int(taxa_acerto * 100))

86
