In [2]:
import tensorflow as tf
import numpy as np

In [3]:
#forecasters attributes
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
x

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [4]:
#answers/ outputs
y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [5]:
#weights
w = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(w)

Instructions for updating:
Colocations handled automatically by placer.


tensorflow.python.ops.variables.RefVariable

In [18]:
#Step Function
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [9]:
print(w)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64_ref>


In [6]:
init = tf.global_variables_initializer()

In [7]:
camada_saida = tf.matmul(x, w)

In [16]:
camada_saida_ativacao = step(camada_saida)

In [19]:
#Error
erro = tf.subtract(y, camada_saida_ativacao)

In [22]:
#Delta
delta = tf.matmul(x, erro, transpose_a = True)
#Traning
treinamento = tf.assign(w, tf.add(w, tf.multiply(delta, 0.1)))

In [28]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(w))
    #print(sess.run(camada_saida))
    
    #print(sess.run(tf.to_float(tf.math.greater_equal(1, 1))))
    #print(sess.run(step(1)))
    #print('\n')
    #print(sess.run(camada_saida_ativacao))
    #print('\n')
    #print(sess.run(erro))
    #print(sess.run(treinamento))
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        print(erro_total)
        print('Época: ', epoca, 'Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
    w_final = sess.run(w)

[[0.]
 [0.]
 [0.]
 [1.]]
Época:  1 Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época:  2 Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época:  3 Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época:  4 Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época:  5 Erro:  1.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época:  6 Erro:  0.0


In [29]:
w_final

array([[0.5],
       [0.5]])

In [30]:
#Test
camada_saida_teste = tf.matmul(x, w_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
